name: Table Tennis API CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

permissions:
  security-events: write
  contents: read
  actions: read

jobs:
  validate-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Security audit
        run: npm audit --audit-level=moderate
        continue-on-error: true
        
      - name: Check syntax
        run: |
          echo "Checking for syntax errors..."
          node -c server.js
          node -c database.js
          node -c auth.js
          for file in routes/*.js; do
            if [ -f "$file" ]; then
              node -c "$file"
            fi
          done
          echo "✅ Syntax check completed"
          
      - name: Verify Vercel config
        run: |
          if [ -f "vercel.json" ]; then
            echo "✅ Vercel configuration found"
            cat vercel.json
          else
            echo "❌ No vercel.json found"
            exit 1
          fi
          
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
          queries: security-extended
          
      - name: Autobuild
        uses: github/codeql-action/autobuild@v3
        
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:javascript"
          
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=jackfgibson_rapProject
            -Dsonar.organization=jackfgibson
            -Dsonar.sources=.
            -Dsonar.exclusions=node_modules/**,*.md
          
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --results=verified,unknown